import { describe, it, expect } from 'vitest'
import { queryKey } from '@/lib/query-keys'

describe('Admin query keys', () => {
  it('opsDashboard', () => { expect(queryKey.admin.opsDashboard()).toEqual(['admin', 'ops-dashboard']) })
  it('workers', () => { expect(queryKey.admin.workers()).toEqual(['admin', 'workers']) })
  it('workerMetrics', () => { expect(queryKey.admin.workerMetrics()).toEqual(['admin', 'workers', 'metrics']) })
  it('outbox', () => { expect(queryKey.admin.outbox({ status: 'pending' })).toEqual(['admin', 'outbox', { status: 'pending' }]) })
  it('outboxStats', () => { expect(queryKey.admin.outboxStats()).toEqual(['admin', 'outbox', 'stats']) })
  it('deadLetters', () => { expect(queryKey.admin.deadLetters({ resolved: false })).toEqual(['admin', 'dead-letters', { resolved: false }]) })
  it('notifications', () => { expect(queryKey.admin.notifications({ status: 'queued' })).toEqual(['admin', 'notifications', { status: 'queued' }]) })
  it('jobs', () => { expect(queryKey.admin.jobs()).toEqual(['admin', 'jobs']) })
  it('users', () => { expect(queryKey.admin.users({ search: 'test' })).toEqual(['admin', 'users', { search: 'test' }]) })
  it('user', () => { expect(queryKey.admin.user('user-1')).toEqual(['admin', 'users', 'user-1']) })
  it('organizations', () => { expect(queryKey.admin.organizations()).toEqual(['admin', 'organizations']) })
  it('organization', () => { expect(queryKey.admin.organization('org-1')).toEqual(['admin', 'organizations', 'org-1']) })
  it('roles', () => { expect(queryKey.admin.roles()).toEqual(['admin', 'rbac', 'roles']) })
  it('permissions', () => { expect(queryKey.admin.permissions()).toEqual(['admin', 'rbac', 'permissions']) })
  it('featureFlags', () => { expect(queryKey.admin.featureFlags()).toEqual(['admin', 'feature-flags']) })
  it('featureFlag', () => { expect(queryKey.admin.featureFlag('flag-1')).toEqual(['admin', 'feature-flags', 'flag-1']) })
  it('auditLogs', () => { expect(queryKey.admin.auditLogs({ action: 'LOGIN' })).toEqual(['admin', 'audit-logs', { action: 'LOGIN' }]) })
  it('securityDashboard', () => { expect(queryKey.admin.securityDashboard()).toEqual(['admin', 'security', 'dashboard']) })
  it('securityIncidents', () => { expect(queryKey.admin.securityIncidents({ severity: 'critical' })).toEqual(['admin', 'security', 'incidents', { severity: 'critical' }]) })
  it('emailDelivery', () => { expect(queryKey.admin.emailDelivery({ status: 'failed' })).toEqual(['admin', 'email-delivery', { status: 'failed' }]) })
  it('billingPlans', () => { expect(queryKey.admin.billingPlans()).toEqual(['admin', 'billing', 'plans']) })
  it('billingSubscriptions', () => { expect(queryKey.admin.billingSubscriptions()).toEqual(['admin', 'billing', 'subscriptions']) })
  it('billingInvoices', () => { expect(queryKey.admin.billingInvoices()).toEqual(['admin', 'billing', 'invoices']) })
  it('billingRevenue', () => { expect(queryKey.admin.billingRevenue()).toEqual(['admin', 'billing', 'revenue']) })
  it('analytics', () => { expect(queryKey.admin.analytics()).toEqual(['admin', 'analytics']) })
  it('systemConfig', () => { expect(queryKey.admin.systemConfig()).toEqual(['admin', 'system-config']) })
  it('search', () => { expect(queryKey.admin.search('test')).toEqual(['admin', 'search', 'test']) })
})
